application: gopher
version: 1
runtime: go
api_version: go1beta

handlers:
- url: / # OMIT
  static_files: index.html # OMIT
  upload: index\.html # OMIT
- url: /favicon.ico # OMIT
  static_files: favicon.ico # OMIT
  upload: favicon.ico # OMIT
- url: /images
  static_dir: images
- url: /doc
  static_dir: doc
- url: /.*
  script: _go_app
